# Generated by Django 4.0.6 on 2022-12-06 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('event_msg', models.CharField(max_length=2000000)),
            ],
        ),
        migrations.CreateModel(
            name='Warnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('tags_method', models.CharField(max_length=200)),
                ('tags_ac', models.CharField(max_length=200)),
                ('tags_app_device', models.CharField(max_length=200)),
                ('tags_ce', models.CharField(max_length=200)),
                ('tags_cn', models.CharField(max_length=200)),
                ('tags_cs', models.CharField(max_length=200)),
                ('tags_de', models.CharField(max_length=200)),
                ('tags_device', models.CharField(max_length=200)),
                ('tags_dns', models.CharField(max_length=200)),
                ('tags_ds', models.CharField(max_length=200)),
                ('tags_du', models.CharField(max_length=200)),
                ('tags_environment', models.CharField(max_length=200)),
                ('tags_host', models.CharField(max_length=200)),
                ('tags_level', models.CharField(max_length=200)),
                ('tags_np', models.CharField(max_length=200)),
                ('tags_os', models.CharField(max_length=200)),
                ('tags_os_name', models.CharField(max_length=200)),
                ('tags_path', models.CharField(max_length=200)),
                ('tags_param', models.CharField(max_length=200)),
                ('tags_ree', models.CharField(max_length=200)),
                ('tags_resp', models.CharField(max_length=200)),
                ('tags_resps', models.CharField(max_length=200)),
                ('tags_rs', models.CharField(max_length=200)),
                ('tags_rspe', models.CharField(max_length=200)),
                ('tags_rsps', models.CharField(max_length=200)),
                ('tags_sc', models.CharField(max_length=200)),
                ('tags_sce', models.CharField(max_length=200)),
                ('tags_scheme', models.CharField(max_length=200)),
                ('tags_scs', models.CharField(max_length=200)),
                ('tags_tls', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.events')),
            ],
        ),
    ]
